# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkC01QcnbZmlIuAN67agG0rWd29cHxAw
"""

def kasallik_tashxisi(belgi):
  if belgi=="Istima":
    return "Parasitamol iching"
  elif belgi== "Tish og'rig'i":
    return "Qupen iching"
  elif belgi== "Qorin og'rig'i":
    return "Levomitsin"
  elif belgi== "bosh og'rig'i":
    return "Bolnol"
  elif belgi== "bo'g'im og'rig'i":
    return "Indamitatsin"
  elif belgi== "ko'z og'rig'i":
    return "Deksa tabron"
  elif belgi== "O'simta":
    return "Halila"
  elif belgi== "Gripp":
    return "Taylolhot"
  elif belgi== "tomoq":
    return "Septaleta"
  else:
    return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)

def togri_ovqatlanish(belgi):
  if belgi=="nonushta":
    return "tuxum, sasiska, sut, soat_7 dan 8 gacha"
  elif belgi=="tushlik":
    return "kaloriyali ovqatlar, soat_12 dan 13 gacha"
  elif belgi=="ikkinchi tushlik":
    return "yengil ovqatlanish, soat_15:30 dan 16:30 gacha"
  elif belgi=="kechki ovqat":
    return "sabzavot va mevalar soat_18 dan 19 gacha"
  else:
    return "Dietolokga murojaat qiling"
belgi=input("Ovqatlanish paytini kiriting ")
natija=togri_ovqatlanish(belgi)
print(natija)